name: Print Github Context
on:
  pull_request:
    branches: [master]
    
jobs:
  dump_context:
    runs-on: ubuntu-latest
    steps:
    - name: Dump context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
        SECRETS: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "$SECRETS"
