name: Merge dependabot pr
on: 
  workflow_run:
    workflows: ["PR - Build App"]
    types: [completed]
  pull_request:
    types: [labeled]

jobs:
  merge_dependabot_pr:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - name: Approve PR
      - run: gh pr review --approve
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request
      - run: gh pr merge -d -s
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

