name: Merge dependabot pr
on: 
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  merge_dependabot_pr:
    runs-on: ubuntu-latest
#     if: ${{ github.user.login == 'dependabot[bot]' }}
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html.href }}

#       - name: Merge pull request
#         run: gh pr merge -d -s "$PR_URL"
#         env: 
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PR_URL: ${{github.event.pull_request.html.href }}

