name: Merge dependabot pr
on: 
  workflow_run:
    workflows: ["PR - Build App"]
    types: [completed]

jobs:
  merge_dependabot_pr:
    if: |
      github.event.label.name == 'Dependabot'
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        uses:  "actions/github-script@v5"
        with: 
          github-action: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            console.log('>>>>', context)
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repo = context.repo

            await github.rest.pulls.createReview({
              event: "APPROVE",
              owner: repo.owner,
              repo: repo.owner,
              pull_number: pullRequest.number
            })


      - name: Merge pull request
        uses: "actions/github-script@v2"
        with: 
          github-action: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repo = context.repo
            await github.rest.pulls.merge({
              merge_method: "squash",
              owner: repo.owner,
              repo: repo.owner,
              pull_number: pullRequest.number
            })

