name: PR - Run E2E Tests
on:
  pull_request:
    branches: [master]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run e2e tests
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm ci
          npm run test:e2e
